INSERT INTO UTILISATEUR(IDENTIFIANT)
  VALUES ("Emannuel");
INSERT INTO UTILISATEUR(IDENTIFIANT)
  VALUES ("Jean");

INSERT INTO CLIENT(CODE, DATECREA)
  VALUES ("Remi", 20000101);
INSERT INTO CLIENT(CODE, DATECREA)
  VALUES ("Jeanne", 20020202);

INSERT INTO FOURNISSEUR(CODE, DATECREA)
 VALUES ("Charles", 20010603);
INSERT INTO FOURNISSEUR(CODE, DATECREA)
 VALUES ("Victorine", 200107026);

INSERT INTO DEMANDE(CLIENTID)
  VALUES (1);
INSERT INTO SECTION(DEMANDEID, SECTYPE, CONTENT)
  VALUES (1, 0, "Première section de la première demande");